  SELECT B2_FILIAL, B2_COD, B2_LOCAL
    FROM SB2010
   WHERE D_E_L_E_T_  <> '*'
GROUP BY B2_FILIAL,B2_COD,B2_LOCAL
  HAVING count(*) > 1;

  SELECT B1_FILIAL, B1_COD
    FROM SB1010
   WHERE D_E_L_E_T_  <> '*'
GROUP BY B1_FILIAL, B1_COD
  HAVING count(*) > 1;

  SELECT B8_FILIAL,B8_PRODUTO,B8_LOCAL,B8_DTVALID,B8_LOTECTL,B8_NUMLOTE
    FROM SB8010
   WHERE D_E_L_E_T_  <> '*'
GROUP BY B8_FILIAL,B8_PRODUTO,B8_LOCAL,B8_DTVALID,B8_LOTECTL,B8_NUMLOTE
  HAVING count(*) > 1;

  SELECT B9_FILIAL,B9_COD,B9_LOCAL,B9_DATA
    FROM SB9010
   WHERE D_E_L_E_T_  <> '*'
GROUP BY B9_FILIAL,B9_COD,B9_LOCAL,B9_DATA
  HAVING count(*) > 1;

  SELECT BF_FILIAL,BF_LOCAL,BF_LOCALIZ,BF_PRODUTO,BF_NUMSERI,BF_LOTECTL,BF_NUMLOTE
    FROM SBF010
   WHERE D_E_L_E_T_  <> '*'
GROUP BY BF_FILIAL,BF_LOCAL,BF_LOCALIZ,BF_PRODUTO,BF_NUMSERI,BF_LOTECTL,BF_NUMLOTE
  HAVING count(*) > 1;

  SELECT BJ_FILIAL,BJ_COD,BJ_LOCAL,BJ_LOTECTL,BJ_NUMLOTE,BJ_DATA
    FROM SBJ010
   WHERE D_E_L_E_T_  <> '*'
GROUP BY BJ_FILIAL,BJ_COD,BJ_LOCAL,BJ_LOTECTL,BJ_NUMLOTE,BJ_DATA
  HAVING count(*) > 1;

  SELECT BK_FILIAL,BK_COD,BK_LOCAL,BK_LOTECTL,BK_NUMLOTE,BK_LOCALIZ,BK_NUMSERI,BK_DATA
    FROM SBK010
   WHERE D_E_L_E_T_  <> '*'
GROUP BY BK_FILIAL,BK_COD,BK_LOCAL,BK_LOTECTL,BK_NUMLOTE,BK_LOCALIZ,BK_NUMSERI,BK_DATA
  HAVING count(*) > 1;

  SELECT D1_FILIAL,D1_DOC,D1_SERIE,D1_FORNECE,D1_LOJA,D1_COD,D1_ITEM,D1_NUMSEQ,D1_EMISSAO
    FROM SD1010
   WHERE D_E_L_E_T_  <> '*'
GROUP BY D1_FILIAL,D1_DOC,D1_SERIE,D1_FORNECE,D1_LOJA,D1_COD,D1_ITEM,D1_NUMSEQ,D1_EMISSAO
  HAVING count(*) > 1;

  SELECT D2_FILIAL,D2_COD,D2_LOCAL,D2_NUMSEQ,D2_ITEM,D2_EMISSAO
    FROM SD2010
   WHERE D_E_L_E_T_  <> '*'
GROUP BY D2_FILIAL,D2_COD,D2_LOCAL,D2_NUMSEQ,D2_ITEM,D2_EMISSAO
  HAVING count(*) > 1;

  SELECT D3_FILIAL,D3_COD,D3_LOCAL,D3_EMISSAO,D3_NUMSEQ,D3_TM,D3_DOC,D3_ESTORNO
    FROM SD3010
   WHERE D_E_L_E_T_  <> '*'
GROUP BY D3_FILIAL,D3_COD,D3_LOCAL,D3_EMISSAO,D3_NUMSEQ,D3_TM,D3_DOC,D3_ESTORNO
  HAVING count(*) > 1;

  SELECT D5_FILIAL,D5_NUMSEQ,D5_PRODUTO,D5_LOCAL,D5_LOTECTL,D5_NUMLOTE,D5_ORIGLAN,D5_ESTORNO
    FROM SD5010
   WHERE D_E_L_E_T_  <> '*'
GROUP BY D5_FILIAL,D5_NUMSEQ,D5_PRODUTO,D5_LOCAL,D5_LOTECTL,D5_NUMLOTE,D5_ORIGLAN,D5_ESTORNO
  HAVING count(*) > 1;

  SELECT DB_FILIAL,DB_PRODUTO,DB_LOCAL,DB_NUMSEQ,DB_DOC,DB_SERIE,DB_CLIFOR,DB_LOJA,DB_ITEM,DB_TM,DB_LOTECTL,DB_NUMLOTE,DB_NUMSERI,DB_DATA,DB_ATUEST,DB_ESTORNO,DB_LOCALIZ
    FROM SDB010
   WHERE D_E_L_E_T_  <> '*'
GROUP BY DB_FILIAL,DB_PRODUTO,DB_LOCAL,DB_NUMSEQ,DB_DOC,DB_SERIE,DB_CLIFOR,DB_LOJA,DB_ITEM,DB_TM,DB_LOTECTL,DB_NUMLOTE,DB_NUMSERI,DB_DATA,DB_ATUEST,DB_ESTORNO,DB_LOCALIZ
  HAVING count(*) > 1;

  SELECT F1_FILIAL,F1_DOC,F1_SERIE,F1_FORNECE,F1_LOJA,F1_TIPO
    FROM SF1010
   WHERE D_E_L_E_T_  <> '*'
GROUP BY F1_FILIAL,F1_DOC,F1_SERIE,F1_FORNECE,F1_LOJA,F1_TIPO
  HAVING count(*) > 1;

  SELECT F2_FILIAL,F2_DOC,F2_SERIE,F2_CLIENTE,F2_LOJA
    FROM SF2010
   WHERE D_E_L_E_T_  <> '*'
GROUP BY F2_FILIAL,F2_DOC,F2_SERIE,F2_CLIENTE,F2_LOJA
  HAVING count(*) > 1;

  SELECT F4_FILIAL,F4_CODIGO
    FROM SF4010
   WHERE D_E_L_E_T_  <> '*'
GROUP BY F4_FILIAL,F4_CODIGO
  HAVING count(*) > 1;

  SELECT BE_FILIAL,BE_LOCAL,BE_LOCALIZ
    FROM SBE010
   WHERE D_E_L_E_T_  <> '*'
GROUP BY BE_FILIAL,BE_LOCAL,BE_LOCALIZ
  HAVING count(*) > 1;