SELECT SUBSTRING(FT_ENTRADA,1,6) DTENTR,FT_CFOP,FT_ESPECIE,FT_SERIE,COUNT(*) REGISTROS
FROM SFT530 SFT
WHERE SFT.D_E_L_E_T_ <> '*' AND  SUBSTRING(FT_ENTRADA,1,6) = '201410'
GROUP BY SUBSTRING(FT_ENTRADA,1,6) ,FT_CFOP,FT_ESPECIE,FT_SERIE
ORDER BY SUBSTRING(FT_ENTRADA,1,6) ,FT_CFOP,FT_ESPECIE,FT_SERIE

FT_ESPECIE="RPS" .AND. FT_SERIE = '1' .AND. FT_CFOP = '6933' .AND. SUBSTR(DTOS(FT_ENTRADA),1,6) >= "201410" //SERIE = 2
FT_ESPECIE=" " .AND. FT_SERIE = '1' .AND. FT_CFOP = '5102' .AND. SUBSTR(DTOS(FT_ENTRADA),1,6) >= "201410"   //ESPECIE = "NF"
FT_ESPECIE=" " .AND. FT_SERIE = '1' .AND. FT_CFOP = '6108' .AND. SUBSTR(DTOS(FT_ENTRADA),1,6) >= "201410"   //ESPECIE = "NF"
FT_ESPECIE="FAT" .AND. FT_SERIE = ' ' .AND. FT_CFOP $ '1949/2949' .AND. SUBSTR(DTOS(FT_ENTRADA),1,6) >= "201410"   //ESPECIE = "NFS"

SELECT SUBSTRING(F3_ENTRADA,1,6) DTENTR,F3_CFO,F3_ESPECIE,F3_SERIE,COUNT(*) REGISTROS
FROM SF3530 SF3
WHERE SF3.D_E_L_E_T_ <> '*' AND  SUBSTRING(F3_ENTRADA,1,6) = '201410'
GROUP BY SUBSTRING(F3_ENTRADA,1,6) ,F3_CFO,F3_ESPECIE,F3_SERIE
ORDER BY SUBSTRING(F3_ENTRADA,1,6) ,F3_CFO,F3_ESPECIE,F3_SERIE

F3_ESPECIE="RPS" .AND. F3_SERIE = '1' .AND. F3_CFO = '6933' .AND. SUBSTR(DTOS(F3_ENTRADA),1,6) >= "201410" //SERIE = 2
F3_ESPECIE=" " .AND. F3_SERIE = '1' .AND. F3_CFO = '5102' .AND. SUBSTR(DTOS(F3_ENTRADA),1,6) >= "201410" //ESPECIE = "NF"
F3_ESPECIE=" " .AND. F3_SERIE = '1' .AND. F3_CFO = '6108' .AND. SUBSTR(DTOS(F3_ENTRADA),1,6) = "201410" //ESPECIE = "NF"

SELECT FT_PRODUTO,B1_DESC,FT_ESPECIE,FT_SERIE,COUNT(*) REG 
FROM SFT530 SFT
INNER JOIN SB1530 SB1 ON B1_COD = FT_PRODUTO
WHERE SFT.D_E_L_E_T_ <> '*'
AND SB1.D_E_L_E_T_ <> '*'
GROUP BY FT_PRODUTO,B1_DESC,FT_ESPECIE,FT_SERIE
ORDER BY FT_PRODUTO,B1_DESC,FT_ESPECIE,FT_SERIE


SELECT FT_ESPECIE,FT_SERIE,FT_CFOP,FT_CSTPIS,FT_CSTCOF,COUNT(*) NREG 
FROM SFT530 
WHERE D_E_L_E_T_ <> '*' AND FT_CFOP <= '5000'
GROUP BY FT_ESPECIE,FT_SERIE,FT_CFOP,FT_CSTPIS,FT_CSTCOF 
ORDER BY FT_ESPECIE,FT_SERIE,FT_CFOP,FT_CSTPIS,FT_CSTCOF 