SELECT (SELECT B1_GRUPO FROM SB1010 WHERE B1_COD = D1_COD) AS TRB_GRUPO,
         D1_COD AS TRB_COD,
         D1_TES AS TRB_TES,
         SUM(D1_QUANT) AS TRB_QUANT,
         CASE WHEN D1_YCUSTO = 0 THEN (SELECT B2_CM1 FROM SB2010 WHERE B2_COD = D1_COD AND B2_LOCAL = D1_LOCAL) ELSE D1_YCUSTO END TRB_VALOR,
         '' AS TRB_DATA
    FROM SD1010
  WHERE D_E_L_E_T_ <> '*'
     AND D1_FILIAL = '01'
--    AND D1_COD IN (SELECT B9_COD FROM SB9010 WHERE D_E_L_E_T_ <> '*' AND B9_FILIAL = '01' AND B9_LOCAL = D1_LOCAL AND B9_DATA >= '        ' AND B9_COD BETWEEN '               ' AND 'ZZZZZZZZZZZZZ  '


SELECT C1_FILIAL ,C1_NUM    ,C1_ITEM   ,C1_PRODUTO,C1_UM     ,C1_QUANT  ,
       C1_SEGUM  ,C1_QTSEGUM,C1_DATPRF ,C1_LOCAL  ,C1_OBS    ,C1_OP     ,
       C1_CC     ,C1_CONTA  ,C1_ITEMCTA,C1_EMISSAO,C1_COTACAO,C1_DESCRI ,
       C1_FORNECE,C1_LOJA   ,C1_PEDIDO ,C1_ITEMPED,C1_SOLICIT,C1_IDENT  ,
       C1_QUJE   ,C1_TX     ,C1_OK     ,C1_OS     ,C1_IMPORT ,C1_UNIDREQ,
       C1_CODCOMP,C1_CLASS  ,C1_FABR   ,C1_FABRLOJ,C1_NUM_SI ,C1_TPOP   ,
       C1_GRUPCOM,C1_USER   ,C1_QUJE2  ,C1_ORIGEM ,C1_CLVL   ,C1_PROJETO,
       C1_FILENT ,C1_SEQMRP ,C1_VUNIT  ,C1_CONDPAG,C1_CODORCA,C1_RESIDUO,
       C1_QTDORIG,C1_TIPOEMP,C1_ESPEMP ,C1_APROV  ,C1_GERACTR,C1_QTDREEM,
       C1_NOMAPRO,C1_FLAGGCT, D_E_L_E_T_ DELETADOS
  FROM SC1010 SC1
 WHERE C1_FILIAL = 'AA' AND 
       C1_EMISSAO >= '20071105' AND 
       C1_EMISSAO <= '20081231' AND
       C1_USER in ( SELECT Y1_USER FROM SY1010 SY1 WHERE Y1_COD in ( '001   ', '144   ' ) )




select * from SY1010
where Y1_COD in ( '005', '006' )


select * from SC1010
where C1_USER in ( select Y1_USER from SY1010
where Y1_COD in ( '001', '144' ) )

select * 
    from LIQ010 
    where D_E_L_E_T_ <> '*' 
        and LIQ_CODEMP in (select DISTINCT E1_CODEMPR from SE1010 WHERE E1_SALDO > 0) 



select * from SE1010 where E1_SALDO = 0 and E1_BAIXA <> '' and E1_CODEMPR <> ''and D_E_L_E_T_ <> '*'

SELECT *, (SELECT B1_DESCR FROM SB1010 SB1 WHERE SB1.D_E_L_E_T_ <> '*' AND B1_COD = SC6.C6_PRODUTO ) AS B1_DESCR
    FROM SC6010 SC6
    WHERE SC6.D_E_L_E_T_ <> '*' 


SELECT (SELECT A3_NOME FROM SA3010 SA3 WHERE SA3.D_E_L_E_T_ <> '*' AND SA3.A3_COD = SC5.C5_VEND1 ) AS VEND1, 
       (SELECT A3_NOME FROM SA3010 SA3B WHERE SA3B.D_E_L_E_T_ <> '*' AND SA3B.A3_COD = SC5.C5_VEND2 AND SA3.A3_COD <> SA3B.A3_COD) AS VEND2,
    C5_VEND1, C5_VEND2, SC5.*
    FROM SC5010 SC5
    WHERE SC5.D_E_L_E_T_ <> '*'